CONTENT_STORE_HEADERS = {'base_path': object,
                         'content_id': object,
                         'title': object,
                         'description': object,
                         'publishing_app': object,
                         'document_type': object,
                         'details': object,
                         'text': object,
                         'organisations': object,
                         'taxons': object,
                         'step_by_steps': object,
                         'details_parts': object,
                         'first_published_at': object,
                         'public_updated_at': object,
                         'updated_at': object,
                         'finder': object,
                         'facet_values': object,
                         'facet_groups': object,
                         'has_brexit_no_deal_notice': bool,
                         'withdrawn': bool,
                         'withdrawn_at': object,
                         'withdrawn_explanation': object}

CONTENT_STORE_DATES = ['first_published_at',
                       'public_updated_at',
                       'updated_at',
                       'withdrawn_at']
